import React, { useState } from 'react';
import { ShieldAlert, ShieldCheck, AlertOctagon, Download, FileSpreadsheet, ArrowLeft, CheckCircle2, AlertTriangle, ExternalLink, Info, Copy } from 'lucide-react';
import { REGULATORY_LINKS } from '../data/scamGuides';

export default function RiskReportView({ result, jobData, onReset }) {
  const [copiedComplaint, setCopiedComplaint] = useState(false);
  const [activeTab, setActiveTab] = useState('flags'); // 'flags' | 'annotated' | 'complaint'

  if (!result) return null;

  const { score, verdict, badgeColor, summaryText, redFlags, breakdown, highlightedDescription } = result;

  // Determine Badge Styling
  const getBadgeStyle = () => {
    if (badgeColor === 'danger') {
      return { background: 'var(--status-danger-bg)', color: 'var(--status-danger)', border: '1px solid rgba(239, 68, 68, 0.4)', glow: 'var(--shadow-danger)' };
    }
    if (badgeColor === 'caution') {
      return { background: 'var(--status-caution-bg)', color: 'var(--status-caution)', border: '1px solid rgba(245, 158, 11, 0.4)', glow: '0 0 25px rgba(245, 158, 11, 0.2)' };
    }
    return { background: 'var(--status-safe-bg)', color: 'var(--status-safe)', border: '1px solid rgba(16, 185, 129, 0.4)', glow: '0 0 25px rgba(16, 185, 129, 0.2)' };
  };

  const badgeStyle = getBadgeStyle();

  // Export Report Helper
  const handleExportMarkdown = () => {
    const reportText = `# VeriJob Risk Audit Report
Title: ${jobData.title || 'Untitled Job'}
Company: ${jobData.company || 'Not Specified'}
Contact Email: ${jobData.email || 'N/A'}
Risk Score: ${score}/100 (${verdict})

Summary:
${summaryText}

Detected Red Flags (${redFlags.length}):
${redFlags.map((rf, idx) => `${idx + 1}. [${rf.severity}] ${rf.title}: ${rf.explanation}`).join('\n')}

Generated by VeriJob AI Job Scam Detector on ${new Date().toLocaleDateString()}`;

    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `verijob-risk-report-${Date.now()}.md`;
    a.click();
  };

  // FTC / IC3 Complaint Text Generator
  const generateComplaintText = () => {
    return `OFFICIAL SCAM COMPLAINT DRAFT
Incident Date: ${new Date().toLocaleDateString()}
Reported Job Title: ${jobData.title || 'Unknown Position'}
Reported Company Name: ${jobData.company || 'Unknown Entity'}
Suspect Contact Email: ${jobData.email || 'None Provided'}
Job Listing URL: ${jobData.url || 'None Provided'}

Automated Risk Evaluation Index: ${score}/100 (${verdict})

Key Fraudulent Indicators Observed:
${redFlags.map(rf => `- ${rf.title}: ${rf.explanation}`).join('\n')}

Original Job Listing Snippet:
"${jobData.description ? jobData.description.slice(0, 500) + '...' : 'N/A'}"`;
  };

  const handleCopyComplaint = () => {
    navigator.clipboard.writeText(generateComplaintText());
    setCopiedComplaint(true);
    setTimeout(() => setCopiedComplaint(false), 2500);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Top Banner & Radial Risk Score */}
      <div className="glass-card" style={{ padding: '32px', position: 'relative', overflow: 'hidden' }}>
        <div style={{
          position: 'absolute',
          top: '-50px',
          right: '-50px',
          width: '200px',
          height: '200px',
          borderRadius: '50%',
          background: badgeStyle.color,
          filter: 'blur(80px)',
          opacity: 0.15,
          pointerEvents: 'none'
        }}></div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '24px' }}>
          <div>
            <button onClick={onReset} className="btn btn-secondary btn-sm" style={{ marginBottom: '16px' }}>
              <ArrowLeft size={14} /> Back to Analyzer
            </button>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
              <span className="badge" style={{ ...badgeStyle, padding: '6px 16px', fontSize: '0.9rem' }}>
                {verdict.replace(/_/g, ' ')}
              </span>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                Analyzed on {new Date().toLocaleTimeString()}
              </span>
            </div>
            <h2 style={{ fontSize: '1.8rem', fontWeight: 800 }}>
              {jobData.title || 'Job Listing Audit Result'}
            </h2>
            <p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', marginTop: '4px', maxWidth: '650px' }}>
              {summaryText}
            </p>
          </div>

          {/* Score Dial Meter */}
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '24px',
            borderRadius: '24px',
            background: 'rgba(10, 15, 26, 0.8)',
            border: badgeStyle.border,
            boxShadow: badgeStyle.glow,
            minWidth: '180px'
          }}>
            <div style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <svg width="120" height="120" viewBox="0 0 120 120">
                <circle cx="60" cy="60" r="50" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="10" />
                <circle
                  cx="60"
                  cy="60"
                  r="50"
                  fill="none"
                  stroke={badgeStyle.color}
                  strokeWidth="10"
                  strokeDasharray={314}
                  strokeDashoffset={314 - (314 * score) / 100}
                  strokeLinecap="round"
                  transform="rotate(-90 60 60)"
                  style={{ transition: 'stroke-dashoffset 1s ease-in-out' }}
                />
              </svg>
              <div style={{ position: 'absolute', textAlign: 'center' }}>
                <span style={{ fontSize: '2.2rem', fontWeight: 800, color: '#ffffff', lineHeight: 1 }}>
                  {score}
                </span>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block' }}>
                  / 100 Risk
                </span>
              </div>
            </div>
            <span style={{ fontSize: '0.8rem', fontWeight: 700, marginTop: '8px', color: badgeStyle.color }}>
              {score >= 50 ? 'HIGH RISK' : score >= 20 ? 'MODERATE RISK' : 'LOW RISK'}
            </span>
          </div>
        </div>
      </div>

      {/* Category Risk Factor Bars */}
      <div className="grid-2">
        <div className="glass-card" style={{ padding: '24px' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Info size={18} color="var(--primary)" /> Multi-Factor Category Breakdown
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '6px' }}>
                <span>Financial & Payment Traps</span>
                <span style={{ fontWeight: 700 }}>{breakdown.financial}%</span>
              </div>
              <div style={{ height: '8px', borderRadius: '4px', background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
                <div style={{ width: `${breakdown.financial}%`, height: '100%', background: 'linear-gradient(90deg, #6366f1, #ef4444)', transition: 'width 0.8s ease' }}></div>
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '6px' }}>
                <span>Communication & Contact Hygiene</span>
                <span style={{ fontWeight: 700 }}>{breakdown.communication}%</span>
              </div>
              <div style={{ height: '8px', borderRadius: '4px', background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
                <div style={{ width: `${breakdown.communication}%`, height: '100%', background: 'linear-gradient(90deg, #06b6d4, #f59e0b)', transition: 'width 0.8s ease' }}></div>
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '6px' }}>
                <span>Identity Theft & Legal Risks</span>
                <span style={{ fontWeight: 700 }}>{breakdown.identity}%</span>
              </div>
              <div style={{ height: '8px', borderRadius: '4px', background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
                <div style={{ width: `${breakdown.identity}%`, height: '100%', background: 'linear-gradient(90deg, #a855f7, #ef4444)', transition: 'width 0.8s ease' }}></div>
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '6px' }}>
                <span>Psychological Pressure Tactics</span>
                <span style={{ fontWeight: 700 }}>{breakdown.urgency}%</span>
              </div>
              <div style={{ height: '8px', borderRadius: '4px', background: 'rgba(255,255,255,0.08)', overflow: 'hidden' }}>
                <div style={{ width: `${breakdown.urgency}%`, height: '100%', background: 'linear-gradient(90deg, #38bdf8, #f59e0b)', transition: 'width 0.8s ease' }}></div>
              </div>
            </div>
          </div>
        </div>

        {/* Actionable Verification Checklist */}
        <div className="glass-card" style={{ padding: '24px' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <CheckCircle2 size={18} color="var(--status-safe)" /> Actionable Verification Steps
          </h3>

          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '12px', fontSize: '0.88rem' }}>
            <li style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span style={{ color: 'var(--status-safe)', fontWeight: 700 }}>✓</span>
              <span><strong>Cross-Check Official Career Page:</strong> Search the company's official website careers section to ensure this specific job ID exists.</span>
            </li>
            <li style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span style={{ color: 'var(--status-safe)', fontWeight: 700 }}>✓</span>
              <span><strong>Verify Recruiter Identity on LinkedIn:</strong> Confirm the email sender actually holds an HR/Recruiting title at the target company.</span>
            </li>
            <li style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span style={{ color: 'var(--status-safe)', fontWeight: 700 }}>✓</span>
              <span><strong>Refuse Upfront Checks/Fees:</strong> Real employers provide laptops directly or reimburse via official payroll after hire.</span>
            </li>
            <li style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span style={{ color: 'var(--status-safe)', fontWeight: 700 }}>✓</span>
              <span><strong>Demand Video or In-Person Interview:</strong> Never accept an employment offer based purely on instant messaging text chats.</span>
            </li>
          </ul>
        </div>
      </div>

      {/* Main Tabs for Red Flags, Annotated Text & Regulatory Complaint */}
      <div className="glass-card" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', gap: '12px', marginBottom: '20px', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '12px' }}>
          <button
            onClick={() => setActiveTab('flags')}
            className={`btn btn-sm ${activeTab === 'flags' ? 'btn-primary' : 'btn-secondary'}`}
          >
            <ShieldAlert size={14} />
            <span>Flagged Scam Indicators ({redFlags.length})</span>
          </button>

          <button
            onClick={() => setActiveTab('annotated')}
            className={`btn btn-sm ${activeTab === 'annotated' ? 'btn-primary' : 'btn-secondary'}`}
          >
            <FileSpreadsheet size={14} />
            <span>Annotated Text Viewer</span>
          </button>

          {score >= 20 && (
            <button
              onClick={() => setActiveTab('complaint')}
              className={`btn btn-sm ${activeTab === 'complaint' ? 'btn-primary' : 'btn-secondary'}`}
            >
              <AlertOctagon size={14} color="#ef4444" />
              <span>FTC / IC3 Complaint Generator</span>
            </button>
          )}
        </div>

        {/* Tab 1: Red Flags List */}
        {activeTab === 'flags' && (
          <div>
            {redFlags.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
                <CheckCircle2 size={42} color="var(--status-safe)" style={{ marginBottom: '12px' }} />
                <h4 style={{ color: '#ffffff' }}>No Flagged Indicators Detected</h4>
                <p style={{ fontSize: '0.9rem', marginTop: '4px' }}>
                  This job posting did not trigger any of our known scam algorithms.
                </p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                {redFlags.map((flag, idx) => (
                  <div
                    key={idx}
                    style={{
                      padding: '16px',
                      borderRadius: '12px',
                      background: 'rgba(10, 15, 26, 0.6)',
                      border: flag.severity === 'CRITICAL' ? '1px solid rgba(239, 68, 68, 0.4)' : '1px solid rgba(245, 158, 11, 0.3)'
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                      <span style={{ fontSize: '0.95rem', fontWeight: 700, color: '#ffffff', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <AlertTriangle size={16} color={flag.severity === 'CRITICAL' ? '#ef4444' : '#f59e0b'} />
                        {flag.title}
                      </span>
                      <span className={`badge ${flag.severity === 'CRITICAL' ? 'badge-danger' : 'badge-caution'}`}>
                        {flag.severity} RISK (+{flag.weight} pts)
                      </span>
                    </div>
                    <p style={{ fontSize: '0.88rem', color: 'var(--text-muted)', lineHeight: '1.5' }}>
                      {flag.explanation}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Tab 2: Annotated Text Viewer */}
        {activeTab === 'annotated' && (
          <div>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
              Scam trigger phrases highlighted in red/yellow:
            </p>
            <div
              style={{
                padding: '20px',
                borderRadius: '12px',
                background: 'rgba(10, 15, 26, 0.8)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                fontFamily: 'var(--font-sans)',
                fontSize: '0.92rem',
                lineHeight: '1.7',
                whiteSpace: 'pre-wrap'
              }}
              dangerouslySetInnerHTML={{ __html: highlightedDescription || jobData.description }}
            />
          </div>
        )}

        {/* Tab 3: Regulatory Complaint Generator */}
        {activeTab === 'complaint' && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                Pre-formatted complaint draft ready to file with consumer protection agencies:
              </p>
              <button onClick={handleCopyComplaint} className="btn btn-secondary btn-sm">
                <Copy size={14} />
                <span>{copiedComplaint ? 'Copied to Clipboard!' : 'Copy Complaint Text'}</span>
              </button>
            </div>
            <textarea
              readOnly
              value={generateComplaintText()}
              style={{
                width: '100%',
                height: '220px',
                background: 'rgba(10, 15, 26, 0.9)',
                border: '1px solid rgba(239, 68, 68, 0.3)',
                borderRadius: '12px',
                padding: '16px',
                color: '#fca5a5',
                fontFamily: 'var(--font-mono)',
                fontSize: '0.85rem',
                outline: 'none',
                resize: 'none'
              }}
            />
            <div style={{ display: 'flex', gap: '12px', marginTop: '16px' }}>
              <a href={REGULATORY_LINKS.ftc} target="_blank" rel="noreferrer" className="btn btn-danger btn-sm">
                <span>File Report on FTC.gov</span>
                <ExternalLink size={14} />
              </a>
              <a href={REGULATORY_LINKS.ic3} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm">
                <span>File Report on IC3.gov</span>
                <ExternalLink size={14} />
              </a>
            </div>
          </div>
        )}

        {/* Export Buttons Footer */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '24px', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.08)' }}>
          <button onClick={handleExportMarkdown} className="btn btn-secondary">
            <Download size={16} />
            <span>Export Markdown Report</span>
          </button>

          <button onClick={onReset} className="btn btn-primary">
            <span>Analyze Another Job</span>
          </button>
        </div>
      </div>
    </div>
  );
}
